**NUMPY:COVERSION FROM OHTER PYTHON STRUCTURES(EG:LISTS,TUPLES)***

In [1]:
import numpy as np
myarr=np.array([3,2,1],np.int8)
myarr


array([3, 2, 1], dtype=int8)

In [2]:
myarr.shape

(3,)

In [3]:
my_arr=np.array([[1,2,3,4]])

In [4]:
my_arr.shape


(1, 4)

In [5]:
myarr.dtype#prints the datatype of tha array

dtype('int8')

**ARRAY CREATION:CONVERSION FROM OTHER PYTHON STRUCTURE**

In [6]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
listarray.shape#prints the shape value of the array


(3, 3)

In [9]:
listarray.size##prints the size of the array

9

In [10]:
np.array({34,35,35})

array({34, 35}, dtype=object)

**ZEROS**

In [11]:
zeros=np.zeros((2,5))##creates a 2d array of 2,5 filled with '0'

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
rng=np.arange(15)##creates an array of that range starting from 0

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
lspace=np.linspace(1,50,10)#creates an array equally seperated with 10 spaces from 1 to 50

In [16]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
lspc=np.linspace(1,4,4)

In [18]:
lspc

array([1., 2., 3., 4.])

In [19]:
emp=np.empty((4,6))#gives you an empty array of 4,6 with random values

In [20]:
emp

array([[4.67296746e-307, 1.69121096e-306, 9.34609111e-307,
        1.33511018e-306, 1.33511969e-306, 6.23037996e-307],
       [6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [8.90104239e-307, 6.89804132e-307, 9.34605716e-307,
        1.37962456e-306, 1.42418172e-306, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        2.11389826e-307, 1.11260619e-306, 2.46151512e-312]])

In [21]:
emp_like=np.empty_like(lspace)##this copy the size of the older array that you created and gives you an emoty array

In [22]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [23]:
ide=np.identity(45)#creates an 45*45 identity matrix

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
ide.shape

(45, 45)

In [26]:
arr=np.arange(99)#also written as(1,99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
arr.reshape(3,33)#reshapes the array in 3*33;make sure the numbers that you provide their multiple should give the same value ar the size of the array is

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr.ravel()#converts the array into a 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

**NUMPY AXIS**

In [30]:
x=[[1,2,3],[4,5,6],[7,8,10]]

In [31]:
ar=np.array(x)

In [32]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [33]:
ar.sum(axis=0)

array([12, 15, 19])

In [34]:
ar.sum(axis=1)

array([ 6, 15, 25])

In [35]:
ar.T#transpose the array

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [36]:
ar.flat#creates a 1d array

In [37]:
for item in ar.flat:
 print(item)

1
2
3
4
5
6
7
8
10


In [38]:
ar.ndim#number of dimensions

2

In [39]:
ar.size


9

In [40]:
ar.nbytes

36

In [41]:
one=np.array([1,3,4])

In [42]:
one.argmax()#gives the index where the max value is present

2

In [43]:
one.argmin()#gives the index where the min value is present

0

In [44]:
one.argsort()#sort the array in ascending order

array([0, 1, 2], dtype=int64)

In [45]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [46]:
ar.argmin()

0

In [47]:
ar.argmax()

8

In [48]:
ar.argmax(axis=0)#check teh max value in every axis

array([2, 2, 2], dtype=int64)

In [49]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [50]:
ar2=np.array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [51]:
ar+ar2

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 12]])

In [52]:
ar*ar2

array([[ 0,  2,  6],
       [ 0,  5, 12],
       [ 0,  8, 20]])

In [53]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.16227766]])

In [54]:
ar.sum()

46

In [55]:
ar.max()

10

In [56]:
ar.min()

1

In [57]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [58]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [59]:
type(np.where(ar>5))

tuple

In [60]:
np.count_nonzero(ar)

9

In [61]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [62]:
ar[1,2]=0

In [63]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [64]:
import sys

In [65]:
ch_ar=[0,4,55,2]

In [66]:
np_ar=np.array(ch_ar)

In [67]:
sys.getsizeof(1)*len(ch_ar)#prints the size of one element present in the array

112

In [68]:
np_ar.itemsize * np_ar.size#numpy size

16

In [70]:
np_ar.tolist()

[0, 4, 55, 2]